### PR TITLE
Add repos synchronization tool

### PR DESCRIPTION
**Pull request by Yikun**
We need a tool to do the synchronization from github to gitee, and then use this tool to do the auto-sync periodically.

This patch add a script will fetch all repos from github, and then push them (include commits, branch, tags) to gitee mirror repo.

Close: #2

### CODE REVIEW

**Comment by Yikun** [comment]
image

The tools demo as above.

**Comment by TommyLike** [comment]
missing shell header.

**Comment by Yikun** [comment]
> missing shell header.

Good catch, and fixed.

**Comment by ZhengZhenyu** [comment]
Overall looks good, but got one thing in my head, this seems can be with very low effeciency if we got a lot of repos, probably we could think of some improvement in the future.

**Comment by Yikun** [comment]
Thanks for the review.

After the consideration of the DRY (Don't Repeat Yourself) principle, this synchronization tool has been replaced by the github action -- [Gitee Mirror Action](https://github.com/marketplace/actions/mirror-the-github-organization-repos-to-gitee) [1].

And now this Gitee Mirror Action v0.01 has been released, so I submited the PR https://github.com/kunpengcompute/Kunpeng/pull/4 to use it in Kunpeng org. If you have the same requirement on the sync between gitee and github, you could see it as the reference. 

Hope you guys have a good exp on trying it.
cc: @TommyLike @leonwanghui @edisonxiang @hannibalhuang @liyongle 

[1] https://github.com/marketplace/actions/mirror-the-github-organization-repos-to-gitee

**Pull request closed without merging**
